extensions:
  - ".github/schema/checks.py"
type: map
func: check_root
mapping:
  Name:
    type: str
    pattern: '^[a-z0-9_\-\.]+\.(dll|ocx)$'
    required: true

  Author:
    type: str
    pattern: '^\w[\w\s\-'']+\w$'
    required: true

  Created:
    type: date
    format: "%Y-%m-%d"
    required: true

  Vendor:
    type: str
    pattern: '^\w[\w|\s|\-]*\w$'
    required: true

  CVE:
    type: str
    pattern: '^CVE-\d{4}-\d{3,}$'
    required: false

  ExpectedLocations:
    type: seq
    required: false
    sequence:
      - type: str
        pattern: '^[%cC][ a-zA-Z0-9&_\-\\%\.\(\):]+(?<!\\)(?<!\.\w{3})$'
        desc: Only backslashes, no trailing slashes, folder paths only (so no filenames)
        unique: true
        required: true

  ExpectedVersionInformation: &VersionInformation
    type: seq
    required: false
    sequence:
      - type: map
        func: not_empty
        mapping:
          CompanyName:
            type: str
            required: false
          FileDescription:
            type: str
            required: false
          FileVersion:
            type: str
            required: false
          InternalName:
            type: str
            required: false
          LegalCopyright:
            type: str
            required: false
          OriginalFilename:
            type: str
            required: false
          ProductName:
            type: str
            required: false
          ProductVersion:
            type: str
            required: false

  ExpectedSignatureInformation: &SignatureInformation
    type: seq
    required: false
    sequence:
      - type: map
        func: not_empty
        mapping:
          Subject:
            type: str
            pattern: '^(?i)((CN|C|O|L|C|OU|S|ST|STREET|PostalCode|SERIALNUMBER|OID(\.\d+)+)=(".+?(?<!\\)"|''.+?(?<!\\)''|([^,]|\\,)+?(?<!\\))(,\s*(?<!$)|$))+$'
            required: false
          Issuer:
            type: str
            pattern: '^(?i)((CN|C|O|L|C|OU|S|ST|STREET|PostalCode|SERIALNUMBER|OID(\.\d+)+)=(".+?(?<!\\)"|''.+?(?<!\\)''|([^,]|\\,)+?(?<!\\))(,\s*(?<!$)|$))+$'
            required: false
          Type:
            type: str
            required: true
            enum: ["Authenticode", "Catalog", "None"]

  VulnerableExecutables:
    type: seq
    required: true
    sequence:
      - type: map
        func: check_executables
        mapping:
          Path:
            type: str
            required: true
            unique: true
            pattern: '^[ a-zA-Z0-9&_\-\\%\.\(\)]+$'

          Type:
            type: str
            enum: ["Sideloading", "Phantom", "Search Order", "Environment Variable"]
            required: true

          AutoElevate:
            type: bool
            required: false

          PrivilegeEscalation:
            type: bool
            required: false

          Condition:
            type: str
            required: false

          SHA256:
            type: seq
            required: false
            sequence:
              - type: str
                pattern: "^[a-zA-Z0-9]{64}$"
                required: true

          Variable:
            type: str
            required: false

          ExpectedVersionInformation:
            <<: *VersionInformation

          ExpectedSignatureInformation:
            <<: *SignatureInformation

  Resources:
    type: seq
    required: false
    sequence:
      - type: str
        required: true
        unique: true
        pattern: '^([^:\/?#]+:)(?:\/\/([^\/?#]*))?([^?#]+)?(\?[^#]*)?(#.*)?'

  Acknowledgements:
    type: seq
    required: false
    sequence:
      - type: map
        func: not_empty
        required: true
        mapping:
          Name:
            type: str
            pattern: '^\w[\w\s\-'']+\w$'
            required: true
          Twitter:
            type: str
            pattern: '^@(\w){1,15}$'
            required: false
